<!doctype html>
<html lang="fr_FR">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Peperoonii Prods, mon site professionnel pour s'acheter pleins d'instrumentales !">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Peperoonii Prod</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="../img/favicon-32x32.png">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css" integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css" integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw==" crossorigin="anonymous" />
    <link rel="stylesheet" href="../css/normalize.css">
    <link rel="stylesheet" href="../css/fonts.css">
    <link rel="stylesheet" href="../css/style.css">
</head>
<header>
    <div class="logo-and-tab">
        <a href="../home.php" class="logo"><img src="../img/Logo PP_Simple.png" alt="Logo du Projet"></a>
        <div class="header-tab">
            <div class="non-authentificated">
        <a href="../login.php" class="sign-up">Se Connecter</a>
            </div>
        <a href="#" class="cart"><i class="fas fa-shopping-cart"></i></a>
        </div>
    </div>
</header>
<body>
    <main>
        <div id="login-box">
            <h1>S'inscrire</h1>
            <form action="../login.php" method="post" enctype="multipart/form-data">
                <input type="hidden" name="signin">
                <input type="text" id="login" name="pseudo" placeholder="Pseudo">
                <input type="email" id="email" name="email" placeholder="Email">
                <input type="file" id="avatar" class="form-control" name="avatar" placeholder="avatar">
                <input type="text" id="password" name="mdp" placeholder="Mot de passe">
                <input type="submit" value="S'inscrire">
            </form>
        </div>
    </main>
        <footer>
            <div class="info">
                <div class="info-details">
                    <i class="fab fa-paypal"></i>
                    <h3>Paiement Securisé</h3>
                    <p>Chaque paiement s'effectue de manière sécurisé par Paypal. Vos données resteront confidentielles.</p>
                </div>
                <div class="info-details">
                    <i class="fas fa-arrow-circle-down"></i>
                    <h3>Téléchargement Immédiat</h3>
                    <p>Une fois la licence achetée, un lien exclusif vous est délivré pour télécharger instantanément la production.</p>
                </div>
                <div class="info-details">
                    <img src="img/waveform.png">
                    <h3>Instrumentales De Haute-Qualité</h3>
                    <p>Chaque instrumentale est délivrée avec la meilleure qualité de son et un mixage travaillé, idéal tant pour travailler en studio que chez soi.</p>
                </div>
            </div>
            <div class="footer">
                <a href="#" class="footer-logo"><img src="../img/Logo PP_Simple.png"/></a>
                <div class="footer-flex">
                    <div class="footer-contact">
                        <h4>Contact</h4>
                        <ul class="contact">
                            <li>Mail : <a href="mailto:peperooniiprod@gmail.com">peperooniiprod@gmail.com</a></li>
                            <li>Téléphone : <a href="tel:+33789616798">07 89 61 67 98</a></li>
                        </ul>
                    </div>
                    <div class="footer-social">
                        <h4>Reseaux</h4>
                        <ul class="social-networks">
                            <li><a href="https://www.instagram.com/pepe_roonii/"><i class="fab fa-instagram"></i></a></li>
                            <li><a href="https://soundcloud.com/mathis-chenut"><i class="fab fa-soundcloud"></i></a></li>
                            <li><a href="https://www.facebook.com/mathis.chenut"><i class="fab fa-facebook-f"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
        <script type="text/javascript" src="../js/script.js"></script>
        <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
</body>
</html>