<!doctype html>
<html lang="fr_FR">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Peperoonii Prods, mon site professionnel pour s'acheter pleins d'instrumentales !">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Peperoonii Prod</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="img/favicon-32x32.png">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/fonts.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<header>
    <div class="logo-and-tab">
        <a href="home.php" class="logo"><img src="img/Logo PP_Simple.png" alt="Logo du Projet"></a>
        <div class="header-tab">
            <div class="non-authentificated">
        <a href="login.php" class="sign-up">S'inscrire | Se Connecter</a>
            </div>
        <a href="#" class="cart"><i class="fas fa-shopping-cart"></i></a>
        </div>
    </div>